### ISSUE TITLE
Transfer Syntax not supported

### ISSUE THREAD

**Issue by muschellij2** [tractor/tractor#3]
Getting 
```r
tractor.base::readDicomFile("test.dcm")
```
```
Output level is not set; defaulting to "Info"
* ERROR: Transfer syntax 1.2.840.10008.1.2.4.70 is not supported
```

I sent the test file to your email to give you an example.  Is this related to JPEG2000 compression?  I was wondering what transfer syntax is supported?  

It works with:
```
tractor.base::readDicomFile("test.dcm", ignoreTransferSyntax=TRUE)
```
and in some instances I'm just trying to dump the header, not read the data - so that works.  

I'm really interested in how this affects the DICOM sorting though.

Either way - probably not a "bug", but figured it may be a good case to discuss

**Comment by jonclayden** [comment]
Transfer syntax 1.2.840.10008.1.2.4.70 [is lossless JPEG](https://www.dicomlibrary.com/dicom/transfer-syntax/), and I have no plans to support reading compressed pixel data from TractoR's internal DICOM-handling functions—using `divest` (or `dcm2niir` 😉) is the way to go for getting the data in this case.

But the metadata is invariably explicit little-endian for these transfer syntaxes, so I've made a commit which will make that assumption and press on, only producing an error if you actually try and read the pixel values. Hence, `readDicomFile` will work on this kind of file, as will sorting. (I've tried both, and it looks good.)

Does that seem reasonable?

**Comment by jonclayden** [comment]
To answer your question more directly, supported transfer syntaxes are the three standard uncompressed ones: implicit little-endian (1.2.840.10008.1.2), explicit little-endian (1.2.840.10008.1.2.1) and explicit big-endian (1.2.840.10008.1.2.2).

**Comment by muschellij2** [comment]
Sounds good - thanks for the response.   I didn't even think of divest, but
duh, that'd be a good next spot.

dcm2niir is only a shotgun converter, so I probably have to really get on
dcmtk: https://github.com/muschellij2/dcmtk ...

Thanks for the solution

John
