### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by resynth1943** [tractor/tractor#4]
Are you still using the Analytics in the documentation?

**Comment by jonclayden** [comment]
Hi – can you clarify what you mean, please? Are you referring to Google Analytics? The documentation is essentially an offline copy of the project web site, so it includes GA code as a result.

**Comment by resynth1943** [comment]
Hi, well the documentation in docs/ uses Google Analytics. Just asking because the project seems to be dead now (?). There's no real point running proprietary tracking if you don't care about the data, which is why I asked.

**Comment by jonclayden** [comment]
The project isn't dead – it has just been quiet during the pandemic lockdown period – but I agree that the GA code doesn't need to be there. I'll tweak the scripts to drop it in the offline version. Thanks.

**Comment by resynth1943** [comment]
Oh awesome, thank you :D Been rather interested in this project, looks like I have a lot to catch up on
