### ISSUE TITLE
expandFileName can't handle Windows UNC paths

### ISSUE THREAD

**Issue by howff** [tractor/tractor#5]
I have to access DICOM files on Windows in paths such as `\\Server\directory` which means using R code such as: `path <- '\\\\Server\\directory'`.
Interestingly R's `.Platform$file.sep == '/'` on Windows, so filenames end up looking like this: `filename <- '\\\\Server\\directory/subdir/file.dcm'`
Your expandFileName function doesn't seem to handle such paths as it's looking for a drive letter so reading files always fails or returns NULL (with no explanatory error message!).https://github.com/tractor/tractor/blob/da7a94b26c36e4666e62a39917e7b662d414a989/tractor.base/R/misc.R#L392

**Comment by howff** [comment]
Suggested fix is to match \\ at the start of the fileName, eg:

```
fileName <- ifelse(fileName %~% "^([A-Za-z]:[/\\\\]|\\\\|/)", fileName, file.path(base,fileName))
```

**Comment by jonclayden** [comment]
Yes, that's the effect of the fix in commit f157b4a, although I've written it differently. Thanks for flagging this up!

**Comment by howff** [comment]
Thanks for fixing this!
Any idea how/when it'll get into CRAN?

**Comment by jonclayden** [comment]
I've put out an interim release this weekend, so it's on CRAN now.
